import { Inter, Archivo } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cashmarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${inter.variable} antialiased`}
      >
        <div className="modal"></div>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}

