// Styles
import "./globals.css";
// Fonts
import { Inter, Archivo } from "next/font/google";
// Context
import { ModalProvider } from "@/context/ModalContext";
import { DarkProvider } from "@/context/DarkContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cashmarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} ${inter.variable} antialiased`}>
        <DarkProvider>
          <ModalProvider>{children}</ModalProvider>
        </DarkProvider>
      </body>
    </html>
  );
}
